#!/bin/bash

PARSED_OPTIONS=""
while getopts "c:p:" options; do
  PARSED_OPTIONS="${PARSED_OPTIONS} -${options}${OPTARG}"
  case $options in
    c )
        CHILD_DEPTH=$OPTARG
        ;;
    p )
        PROJECT_ID=$OPTARG
        ;;
   \? ) 
        exit 1
        ;;
  esac
done
shift $(( OPTIND - 1 ));


