#!/bin/bash

function assert_json() {
  echo "$1" | jq -e '.' >/dev/null 2>&1 && echo "1"
}

function json_lines_to_json_array() {
    local JSON_LINES="$1"
    local IFS=$'\n'
    local LINES_ARRAY=(${JSON_LINES})
    local JSON_ARRAY="["
    local FIRST_ELEMENT=1
    for JSON in "${LINES_ARRAY[@]}"; do
      if [ "$FIRST_ELEMENT" -eq 1 ];then
        FIRST_ELEMENT=0
        JSON_ARRAY="${JSON_ARRAY}${JSON}"
      else
        JSON_ARRAY="${JSON_ARRAY},${JSON}"
      fi
    done
    local JSON_ARRAY="$JSON_ARRAY]"
    echo "$JSON_ARRAY"
}

function ids_from_json_array() {
  echo "$(echo "$1" | jq '.[]|.id')"
}

#function load_json_content_for_ids
#function parse_custom_json_field
#function load_json_content_of_children


