#!/bin/bash

function task_line_from_json(){
    : ${SPACES:=''}
    if [ "${EXTENDED}" == "1" ]; then
      # TODO: when the description contains new lines ('\r\n')
      #       the result is strange
      jq -r -c "(if type == \"array\" then .[] else . end |\
\"${SPACES}\(.id): [\(.spent_hours//\"!\")-\(.remaining_hours//\"!\")-\(.estimated_hours//\"!\")] \(.status_name) [\(.assigned_to_name)] : \(.subject) - \(.parent_id//\"\") \
\(.fixed_version_name) \
\(if (.description != null) and (.description != \"\") then (\"\n${SPACES}    \(.description)\") else \"\" end) \
\(if (.notes | length) > 0 then ([.notes[] |\"\n${SPACES}    note: \(.notes)\"]| add ) else \"\" end) \
\"\
      )"
#\"${SPACES}\(.id): [\(.spent_hours//\"!\")-\(.remaining_hours//\"!\")-\(.estimated_hours//\"!\")] \(.status_name) [\(.assigned_to_name)] : \(.subject) - \(.parent_id) \(. fixed_version_name//\"\")\"\
    else
      echo "$1" | jq -r "(if type == \"array\" then .[] else . end |\
\"${SPACES}\(.id): [\(.spent_hours//\"!\")-\(.remaining_hours//\"!\")-\(.estimated_hours//\"!\")] \(.status_name) [\(.assigned_to_name)] : '\(.subject)'\"\
      )"
    fi
}

if [ "$#" -ge 1 ]; then
  if [ "$1" = "lines" ]; then
    shift
    load_json_content_of_ids
    TASK_JSON_LINES="$(echo "$ALL_TASKS_JSON" | jq -c '.[]')"

    OLD_IFS="$IFS"
    IFS=$'\n'
    IFS=${IFS:0:1}
    TASK_JSONS=(${TASK_JSON_LINES})
    IFS=$OLD_IFS

    for TASK_JSON in "${TASK_JSONS[@]}"; do
      task_line_from_json "$TASK_JSON"
    done

  elif [ "$1" = "childlines" ]; then
    shift
    load_json_content_of_ids
    echo ">>>>>>>>>>>>>"

  elif [ "$1" = "pretty" ]; then
    shift
    load_json_content_of_ids
    echo "$ALL_TASKS_JSON" | jq '.'

  elif [ "$1" = "json" ]; then
    shift
    load_json_content_of_ids
    echo "$ALL_TASKS_JSON"

  elif [ "$1" = "ids" ]; then
    shift
    echo "$IDS"
  fi
else
  echo "$IDS"
fi

