#!/bin/bash

function assert_json() {
  echo "$1" | jq -e '.' >/dev/null 2>&1 && echo "1"
}

function json_lines_to_json_array() {
  local JSON_LINES="$1"
  local IFS=$'\n'
  local LINES_ARRAY=(${JSON_LINES})
  local JSON_ARRAY="["
  local FIRST_ELEMENT=1
  for JSON in "${LINES_ARRAY[@]}"; do
    if [ "$FIRST_ELEMENT" -eq 1 ];then
      FIRST_ELEMENT=0
      JSON_ARRAY="${JSON_ARRAY}${JSON}"
    else
      JSON_ARRAY="${JSON_ARRAY},${JSON}"
    fi
  done
  local JSON_ARRAY="$JSON_ARRAY]"
  echo "$JSON_ARRAY"
}

function write_issue() {
  local ISSUE_ID=$1
  local VALUES=$2
  local CURL_STRING=$(echo "$VALUES" | sed -e "s/^/{'issue':{/g" -e "s/$/}}/g" -e "s/'/\"/g")
  echo "$CURL_STRING" |\
  curl -X PUT -H "Content-type:application/json" -s -3 -d @- "https://${SERVER}/issues/${ISSUE_ID}.json?key=${KEY}"
}

function modify_custom_json() {
  local ID="$1"
  local JSON="$2"  
  local JSON_MODIFICATION="$3"
  local OLD_VALUE=$(echo "$JSON" | jq -r ".description")
  if [ $(assert_json "$OLD_VALUE") ]; then
    #redtask 3126 des "{\\\"hi\\\":4}"
    # $2='.a="4" | .b=5'
    if [ -z "$OLD_VALUE" ];then
      #echo "old description was empty"
      local OLD_VALUE="{}"
    fi
  else
    local OLD_VALUE="{}"
    echo "old description was not a json content" 1>&2
  fi

  local NEW_VALUE=$(echo "$OLD_VALUE" | jq -c "$JSON_MODIFICATION" | sed -e 's/"/\\\"/g')
  #echo "New: $NEW_VALUE" 1>&2
  write_issue $ID "'description':'$NEW_VALUE'"
}

function modifier_string_for_custom_json() {
  local JSON="$1"
  local JSON_MODIFICATION="$2"
  local OLD_VALUE=$(echo "$JSON" | jq -r ".$CUSTOM_JSON_KEY")
  if [ $(assert_json "$OLD_VALUE") ]; then
    if [ -z "$OLD_VALUE" ];then
      local OLD_VALUE="{}"
    fi
  else
    local OLD_VALUE="{}"
    echo "old description was not a json content!" 1>&2
  fi
  local NEW_VALUE=$(echo "$OLD_VALUE" | jq -c "$JSON_MODIFICATION" | sed -e 's/"/\\\"/g')
  echo "'$CUSTOM_JSON_KEY':'$NEW_VALUE'"
}


function ids_from_json_array() {
  echo "$(echo "$1" | jq '.[]|.id')"
}

function project_members() {
  curl -s -3 "https://$SERVER/projects/$PROJECT_ID/memberships.json?key=$KEY" |\
  jq -c '.memberships'
  #jq -r '(.memberships[] | .user | "\(.name) : \(.id)")'
}

function project_member_by_name() {
  local USER_NAME_STRING="$1"
  local ALL_MEMBERS_JSON="$(project_members | tr '[:upper:]' '[:lower:]')"
  local MATCHING_USER_IDS="$(echo "$ALL_MEMBERS_JSON" | jq "[.[] | select(.user.name | contains(\"$USER_NAME_STRING\")) | .user.id]")"
  local MATCHING_USER_IDS_COUNT="$(echo "$MATCHING_USER_IDS" | jq 'length')"
  if [ "$MATCHING_USER_IDS_COUNT" -eq 1 ];then
    local MATCHING_USER_ID="$(echo "$MATCHING_USER_IDS" | jq '.[]')"
    echo "$MATCHING_USER_ID"
  else
    echo
  fi
}


#TODO:
function load_json_content_for_ids() {
  :
}

function parse_custom_json_field() {
  local JSON_CONTENT="$1"
  local CONTENT_IDS="$2"
  for ID in $CONTENT_IDS; do
    local DESCRIPTION=$(echo "$JSON_CONTENT" | jq -r -c ".[]| select(.id==$ID) |.$CUSTOM_JSON_KEY")
    if [ -n "$DESCRIPTION" ] && [ $(assert_json "$DESCRIPTION") ]; then
      #echo "DESCRIPTION IS JSON" 1>&2
      local JSON_CONTENT=$(echo "$JSON_CONTENT" |\
        jq -c "[.[] | if .id==$ID then .cjson=$DESCRIPTION else . end]"\
        )
    fi
  done
  echo "$JSON_CONTENT" 
}

#TODO:
function load_json_content_of_children() {
  :
}


