#!/bin/bash

while true;do
  if [ "$#" -ge 1 ]; then
    if [ $(echo "$1" | grep "^[0-9]*\(,[0-9]*\)*$") ]; then
      IDS=$(echo "$1" | tr ',' '\n')
      shift

    elif [ $(echo "$1" | grep "ids:[a-zA-Z0-9_-]\{1,\}") ]; then
      VARIABLE_NAME=$(echo "$1" | sed 's/^ids://g')
      shift
      #TODO: how to append to existing id list
      IDS="$(eval $VARIABLE_NAME)"

    elif [ $(echo "$1" | grep "json:stdin") ]; then
      shift
      #TODO: how to append exisiting json
      ALL_TASKS_JSON="$(cat)"
      IDS="$( ids_from_json_array "$ALL_TASKS_JSON" )"
      ALL_TASKS_JSON="$(parse_custom_json_field "$ALL_TASKS_JSON" "$IDS")"

    elif [ $(echo "$1" | grep "json:[a-zA-Z0-9_-]\{1,\}") ]; then
      VARIABLE_NAME=$(echo "$1" | sed 's/^json://g')
      shift
      #TODO: how to append exisiting json
      ALL_TASKS_JSON="$(eval $VARIABLE_NAME)"
      IDS="$( ids_from_json_array "$ALL_TASKS_JSON" )"
      ALL_TASKS_JSON="$(parse_custom_json_field "$ALL_TASKS_JSON" "$IDS")"

    else
      break
    fi
  else
    break
  fi
done

