#!/bin/bash

function print_desc() {
  local JSON="$1"
  local LEADING_SPACES="$2"
  print_default "$JSON" "$LEADING_SPACES" | tr -d '\n'

  DESCRIPTION="$(echo "$JSON" | jq -r '.description//""')"
  if [ -n "$DESCRIPTION" ];then
    echo
    echo "$DESCRIPTION" \
    | sed '/@[^:]*:/d' \
    | sed -e "s/^/${LEADING_SPACES}${CHILD_LEADING_SPACES}${CHILD_LEADING_SPACES}/g" \
    | sed -e "s/^\(.\{$(tput cols)\}\).*$/\1/g"
  else
    echo
  fi
}

function print_details() {
  local JSON="$1"
  local LEADING_SPACES="$2"
  print_default "$JSON" "$LEADING_SPACES" | tr -d '\n'

  echo -n "$(echo "$JSON" | jq -r "\
if (.release.release.name != null) then \"\n${LEADING_SPACES}${CHILD_LEADING_SPACES}${CHILD_LEADING_SPACES}\
release: \(.release.release.name) (\(.release.release.id))\" else \"\" end" |\
    sed -e "s/^\(.\{$(tput cols)\}\).*$/\1/g")"

  NOTES="$(echo "$JSON" | jq -c "\
if (.journals != null) then \
[.journals[] | select(.notes != \"\") | { a: .user.name, b: .notes } ] \
else [] end \
")"
  if [ "$NOTES" != "[]" ];then
    echo
    echo -n "$( echo "$NOTES" |\
    jq ".[] | \"${LEADING_SPACES}${CHILD_LEADING_SPACES}${CHILD_LEADING_SPACES}\
note: \(.a): \(.b)\" "\
    |sed -e 's/^"//g' -e 's/"$//g'\
    |sed -e "s/^\(.\{$(tput cols)\}\).*$/\1/g"\
    )"
  fi

  DESCRIPTION="$(echo "$JSON" | jq -r '.description//""')"
  if [ -n "$DESCRIPTION" ];then
    echo
    echo "$DESCRIPTION" \
    | sed -e "s/^/${LEADING_SPACES}${CHILD_LEADING_SPACES}${CHILD_LEADING_SPACES}/g" \
    | sed -e "s/^\(.\{$(tput cols)\}\).*$/\1/g"
  else
    echo
  fi
}

function print_default() {
  local JSON="$1"
  local LEADING_SPACES="$2"
  #local FEATURE=$(echo "$JSON" | jq -r 'if .tracker_name == "Feature" then 1 else 0 end')
  #TODO: replace fixed issue tracker id with variable
  #local FEATURE=$(echo "$JSON" | jq -r 'if .tracker.id == 4 then 1 else 0 end')
  local TASK=$(echo "$JSON" | jq -r 'if .tracker.name == "Task" then 1 else 0 end')
  if [ "$TASK" -eq 1 ]; then
    LINE="$(echo "$JSON" |\
    jq -r \
"\"$LEADING_SPACES\
\(.id)\
 [\
\(.estimated_hours//\"-\")\
]\
\(if (.cjson.est!= null) then \"\(.cjson.est)\" else \"\" end)\
 \(.status.name)\
\(if ( (.cjson.tags != null) and ((.cjson.tags|length) > 0) ) then \" (\(.cjson.tags|join(\",\")))\" else \"\" end )\
\(if (.category.name!=null) then \" (\(.category.name))\" else \"\" end)\
\(if (.assigned_to.name!=null) then \" \(.assigned_to.name)\" else \"\" end):\
 \\\"\(.subject)\\\"\
\"" |\
    sed -e "s/^\(.\{$(tput cols)\}\).*$/\1/g")"

    #local STATUS_IN_WORK=$(echo "$JSON" | jq -r 'if .status.id == 2 then 1 else 0 end')
    #if [ "$STATUS_IN_WORK" -eq 1 ]; then
    #echo ">>>>>>>>>>>>$(echo "$JSON" | jq -r '.status.id')"
    if [ "$(echo "$JSON" | jq -r 'if .status.id == 2 then 1 else 0 end')" = "1" ];then
      tput bold
      tput setaf 2
      echo "$LINE"
      tput sgr0
    elif [ "$(echo "$JSON" | jq -r 'if ((.status.id == 5)or(.status.id==6)) then 1 else 0 end')" = "1" ];then
      tput bold
      tput setaf 1
      echo "$LINE"
      tput sgr0
    else
      tput bold
      tput setaf 6
      echo "$LINE"
      tput sgr0
    fi
  #elif [ "$FEATURE" -eq 1 ]; then
  else
    LINE="$(echo "$JSON" |\
    jq -r \
"\"$LEADING_SPACES\
\(.id)\
 [\(.story_points//\"\"):\(.estimated_hours//\"\"):\(.done_ratio//\"-\")%]\
 \(.status.name)\
 \(.tracker.name)\
\(if ( (.cjson.tags != null) and ((.cjson.tags|length) > 0) ) then \" (\(.cjson.tags|join(\",\")))\" else \"\" end )\
\(if (.category.name!=null) then \" (\(.category.name))\" else \"\" end)\
\(if (.assigned_to.name!=null) then \" \(.assigned_to.name)\" else \"\" end):\
 \\\"\(.subject)\\\"\
\"" |\
    sed -e "s/^\(.\{$(tput cols)\}\).*$/\1/g")"

    tput setaf 5
    echo "$LINE"
    tput sgr0

  fi
}

function print_children_by_their_parent_id(){
  local IDS="$1"
  local PRINT_COMMAND="$2"
  local LEADING_SPACES="$3"

  if [ -z "$IDS" ]; then
      local IDS="$(echo "$FILTERED_TASKS" | jq -c 'map(select(.parent==null)|{id:.id})')"
  fi

  for ID in $(ids_from_json_array "$IDS"); do
    #echo ">$ID<"
    JSON="$(echo "$ALL_TASKS_JSON" | jq -r ".[]| select(.id==$ID)")"
    $PRINT_COMMAND "$JSON" "$LEADING_SPACES"
    for CHILD_JSON in $( echo "$ALL_TASKS_JSON" | jq -c "map(select((.parent!=null) and(.parent.id==$ID) ))|.[]" ); do
      CHILD_ID=$(echo "$CHILD_JSON" | jq -c '[{id:.id}]')
      #echo "CHILD_ID: $CHILD_ID"
      print_children_by_their_parent_id "$CHILD_ID" "$PRINT_COMMAND" "$LEADING_SPACES$CHILD_LEADING_SPACES" 
    done
  done
}

function print_list(){
  local PRINT_COMMAND="$1"
  local LEADING_SPACES="$2"

  JSON="$(echo "$ALL_TASKS_JSON" | jq -c '.[]')"
  for JSON in $( echo "$FILTERED_TASKS" | jq -c ".[]" ); do
    $PRINT_COMMAND "$JSON" "$LEADING_SPACES"
  done
}

while true;do
  if [ "$#" -ge 1 ]; then

    if [ "$1" = "list" ]; then
      shift
      load_json_content_of_ids
      print_list print_default

    elif [ $(echo "$1" | grep "list:[a-zA-Z0-9_-]*") ]; then
      PRINT_COMMAND=$(echo "$1" | sed 's/^list://g')
      shift
      if [ -z "$PRINT_COMMAND" ]; then
        PRINT_COMMAND="print_details"
      fi
      load_json_content_of_ids
      print_list "$PRINT_COMMAND"

    elif [ "$1" = "lines" ]; then
      shift
      #TODO: nothing is printed if no one has parents
      load_json_content_of_ids
      print_children_by_their_parent_id "" print_default

    elif [ "$1" = "lines:desc" ]; then
      shift
      load_json_content_of_ids
      print_children_by_their_parent_id "" print_desc

    elif [ $(echo "$1" | grep "lines:[a-zA-Z0-9_-]*") ]; then
      PRINT_COMMAND=$(echo "$1" | sed 's/^lines://g')
      shift
      if [ -z "$PRINT_COMMAND" ]; then
        PRINT_COMMAND="print_details"
      fi
      load_json_content_of_ids
      print_children_by_their_parent_id "" "$PRINT_COMMAND"

    elif [ "$1" = "report_estimates" ]; then
      shift
      load_json_content_of_ids
      TOTAL_HOURS="0 "
      for TASK_JSON in $( echo "$FILTERED_TASKS" | jq -c '.[]' ); do
        HOURS=$(echo "$TASK_JSON" | jq '.estimated_hours//0')
        TOTAL_HOURS+=" + $HOURS"
      done
      TOTAL_HOURS=$( echo "$TOTAL_HOURS" | bc )
      echo "    :[$TOTAL_HOURS]"

    elif [ $(echo "$1" | grep "^report$") ]; then
      shift
      load_json_content_of_ids
      #TOTAL_ESTIMATED=$(echo "$FILTERED_TASKS" | jq '[.[] | .estimated_hours] | add')
      #TOTAL_ESTIMATED=$(echo "$FILTERED_TASKS" | jq -c '[.[] | .estimated_hours]')
      #echo "total estimated hours: $TOTAL_ESTIMATED"
      TOTAL_HOURS="0 "
      TOTAL_HOURS_WITH_FACTOR="0 "
      for TASK_JSON in $( echo "$FILTERED_TASKS" | jq -c '.[]' ); do
        ID=$(echo "$TASK_JSON" | jq '.id')
        HOURS=$(echo "$TASK_JSON" | jq '.estimated_hours//0')
        COMPLEXITY=$(echo "$TASK_JSON" | jq '.cjson.complexity//0')
        INNOVATION=$(echo "$TASK_JSON" | jq '.cjson.innovation//0')
        PAIRING=$(echo "$TASK_JSON" | jq '.cjson.pairing//0')

        #echo "------------------------------"
        #echo "HOURS:>$HOURS<"
        #echo "COMPLEXITY:>$COMPLEXITY<"
        #echo "INNOVATION:>$INNOVATION<"
        #echo "PAIRING:>$PAIRING<"

        PAIRING_FACTOR=$( echo "1 + $PAIRING / 2" | bc -ql)
        #echo "PAIRING_FACTOR:>$PAIRING_FACTOR<"
        RISK_SELECTOR=$(( COMPLEXITY * 3 + INNOVATION ))
        #echo "RISK_SELECTOR:>$RISK_SELECTOR<"

        RISK_TABLE="[1.1637223975, 1.1980530973, 1.9808695652, 1.5203299941, 1.5320987654, 1.8945454545, 1.7795275591, 1.3245614035, 2.3448275862]"
        #RISK_TABLE="[10,20,30,40,50,60,70,80,90]"
        RISK_FACTOR=$(echo "$RISK_TABLE" | jq -r -c ".[$RISK_SELECTOR]")
        #echo "RISK_FACTOR:>$RISK_FACTOR<"

        FINAL_HOURS=$( echo "scale=2; $RISK_FACTOR * $PAIRING_FACTOR * $HOURS" | bc -ql)
        #echo "FINAL_HOURS:>$FINAL_HOURS<"

        FINAL_HOURS_SHORT=$(printf "%0.1f\n" $FINAL_HOURS)
        #echo "FINAL_HOURS_SHORT:>$FINAL_HOURS_SHORT<"
        echo "$ID: ($HOURS) : $FINAL_HOURS_SHORT"
        TOTAL_HOURS+=" + $HOURS"
        TOTAL_HOURS_WITH_FACTOR+=" + $FINAL_HOURS_SHORT"
      done

      TOTAL_HOURS=$( echo "$TOTAL_HOURS" | bc )
      TOTAL_HOURS_WITH_FACTOR=$( echo "$TOTAL_HOURS_WITH_FACTOR" | bc )
      #echo "TOTAL_HOURS:>$TOTAL_HOURS<"
      #echo "TOTAL_HOURS_WITH_FACTOR:>$TOTAL_HOURS_WITH_FACTOR<"

      echo "    : ($TOTAL_HOURS) :$TOTAL_HOURS_WITH_FACTOR"

    elif [ $(echo "$1" | grep "^report:short$") ]; then
      shift
      load_json_content_of_ids
      #TOTAL_ESTIMATED=$(echo "$FILTERED_TASKS" | jq '[.[] | .estimated_hours] | add')
      #TOTAL_ESTIMATED=$(echo "$FILTERED_TASKS" | jq -c '[.[] | .estimated_hours]')
      #echo "total estimated hours: $TOTAL_ESTIMATED"
      TOTAL_HOURS="0 "
      TOTAL_HOURS_WITH_FACTOR="0 "
      for TASK_JSON in $( echo "$FILTERED_TASKS" | jq -c '.[]' ); do
        ID=$(echo "$TASK_JSON" | jq '.id')
        HOURS=$(echo "$TASK_JSON" | jq '.estimated_hours//0')
        COMPLEXITY=$(echo "$TASK_JSON" | jq '.cjson.complexity//0')
        INNOVATION=$(echo "$TASK_JSON" | jq '.cjson.innovation//0')
        PAIRING=$(echo "$TASK_JSON" | jq '.cjson.pairing//0')

        #echo "------------------------------"
        #echo "HOURS:>$HOURS<"
        #echo "COMPLEXITY:>$COMPLEXITY<"
        #echo "INNOVATION:>$INNOVATION<"
        #echo "PAIRING:>$PAIRING<"

        PAIRING_FACTOR=$( echo "1 + $PAIRING / 2" | bc -ql)
        #echo "PAIRING_FACTOR:>$PAIRING_FACTOR<"
        RISK_SELECTOR=$(( COMPLEXITY * 3 + INNOVATION ))
        #echo "RISK_SELECTOR:>$RISK_SELECTOR<"

        RISK_TABLE="[1.1637223975, 1.1980530973, 1.9808695652, 1.5203299941, 1.5320987654, 1.8945454545, 1.7795275591, 1.3245614035, 2.3448275862]"
        #RISK_TABLE="[10,20,30,40,50,60,70,80,90]"
        RISK_FACTOR=$(echo "$RISK_TABLE" | jq -r -c ".[$RISK_SELECTOR]")
        #echo "RISK_FACTOR:>$RISK_FACTOR<"

        FINAL_HOURS=$( echo "scale=2; $RISK_FACTOR * $PAIRING_FACTOR * $HOURS" | bc -ql)
        #echo "FINAL_HOURS:>$FINAL_HOURS<"

        FINAL_HOURS_SHORT=$(printf "%0.1f\n" $FINAL_HOURS)
        #echo "FINAL_HOURS_SHORT:>$FINAL_HOURS_SHORT<"
        #echo "$ID: ($HOURS) : $FINAL_HOURS_SHORT"
        TOTAL_HOURS+=" + $HOURS"
        TOTAL_HOURS_WITH_FACTOR+=" + $FINAL_HOURS_SHORT"
      done

      TOTAL_HOURS=$( echo "$TOTAL_HOURS" | bc )
      TOTAL_HOURS_WITH_FACTOR=$( echo "$TOTAL_HOURS_WITH_FACTOR" | bc )
      #echo "TOTAL_HOURS:>$TOTAL_HOURS<"
      #echo "TOTAL_HOURS_WITH_FACTOR:>$TOTAL_HOURS_WITH_FACTOR<"

      echo "    : ($TOTAL_HOURS) :$TOTAL_HOURS_WITH_FACTOR"

    elif [ "$1" = "pretty" ]; then
      shift
      load_json_content_of_ids
      echo "$FILTERED_TASKS" | jq '.'

    elif [ "$1" = "json" ]; then
      shift
      load_json_content_of_ids
      echo "$FILTERED_TASKS"

    elif [ "$1" = "ids" ]; then
      shift
      echo "$IDS"

    elif [ "$1" = "csids" ]; then
      shift
      COMMA_SEPARATED_IDS=""
      for ID in $IDS; do
        if [ -z "$COMMA_SEPARATED_IDS" ];then
          COMMA_SEPARATED_IDS="$ID"
        else
          COMMA_SEPARATED_IDS+=",$ID"
        fi
      done
      echo "$COMMA_SEPARATED_IDS"

    elif [ $(echo "$1" | grep "print:[a-zA-Z0-9_-]\{1,\}") ]; then
      VARIABLE_NAME=$(echo "$1" | sed 's/^print://g')
      shift
      eval $VARIABLE_NAME

    else
      break
    fi
  else
    break
  fi
done


