#!/bin/bash

while true; do
  if [ "$#" -ge 1 ]; then

    if [ $(echo "$1" | grep "^spent_time:[a-zA-Z0-9_-]*") ]; then
      USER_STRING=$(echo "$1" | sed 's/^spent_time://g')
      shift
      if [ -z "$USER_STRING" ];then
          DAYS_TO_SHOW=".[-4:]"
          #if [ -n "${TIME_TO_SHOW}" ]; then
          #  DAYS_TO_SHOW=".[-${TIME_TO_SHOW}:]"
          #fi
          curl -s -3 "https://$SERVER/projects/$PROJECT_ID/time_entries.json?limit=${ISSUE_LIMIT}&key=$KEY" |\
          jq '.time_entries' |\
          jq '. | sort_by(.spent_on)' |\
          jq '. | group_by(.spent_on)' |\
          jq "$DAYS_TO_SHOW" |\
          jq -r -c '.[] | "\(.[0].spent_on)", (.[] | "    \(.issue.id): \(.hours): \"\(.comments//"")\""), "          \([.[] | .hours] | add)"' 

          #jq -r -c '.[] | "\(.[0].spent_on)", (.[] | "    \(.issue.id) : \(.hours)    \(.comments//"")"), "    -----------\n           \([.[] | .hours] | add)"' 

          echo "$( date +%F) : today"
      else
        MATCHING_USER_ID="$(project_member_by_name $USER_STRING)"
        if [ -n "$MATCHING_USER_ID" ];then

          DAYS_TO_SHOW=".[-4:]"
          #if [ -n "${TIME_TO_SHOW}" ]; then
          #  DAYS_TO_SHOW=".[-${TIME_TO_SHOW}:]"
          #fi
          curl -s -3 "https://$SERVER/projects/$PROJECT_ID/time_entries.json?limit=${ISSUE_LIMIT}&key=$KEY&user_id=$MATCHING_USER_ID" |\
          jq '.time_entries' |\
          jq '. | sort_by(.spent_on)' |\
          jq '. | group_by(.spent_on)' |\
          jq "$DAYS_TO_SHOW" |\
          jq -r -c '.[] | "\(.[0].spent_on)", (.[] | "    \(.issue.id): \(.hours): \"\(.comments//"")\""), "          \([.[] | .hours] | add)"' 

          #jq -r -c '.[] | "\(.[0].spent_on)", (.[] | "    \(.issue.id) : \(.hours)    \(.comments//"")"), "    -----------\n           \([.[] | .hours] | add)"' 

          echo "$( date +%F) : today"
        fi
      fi

#    elif [ $(echo "$1" | grep "^spent:[0-9]*$") ]; then
#      SPENT_HOURS=$(echo "$1" | sed 's/^spent://g')
#      shift
#      for ID in $IDS; do
#        echo "'hours':'$SPENT_HOURS'" |\
#        sed -e "s/$/,'activity_id':9/g" |\
#        sed -e "s/$/,'issue_id':$ID/g" |\
#        sed -e "s/^/{'time_entry':{/g" -e "s/$/}}/g" -e "s/'/\"/g" |\
#        curl -X POST -H "Content-type:application/json" -s -3 -d @- "https://$SERVER/time_entries.json?key=$KEY" 
#        echo
#      done

#    elif [ $(echo "$1" | grep "^spent:[0-9]*:[0-9]\{2\}-[0-9]\{2\}$") ]; then
#      SPENT_HOURS=$(echo "$1" | sed 's/^spent:\(.*\):.*$/\1/g')
#      SPENT_ON="$(date +%Y)-$(echo "$1" | sed 's/^spent:.*:\(.*\)$/\1/g')"
#      shift
#      for ID in $IDS; do
#        echo "'hours':'$SPENT_HOURS'" |\
#        sed -e "s/$/,'spent_on':'$SPENT_ON'/g" |\
#        sed -e "s/$/,'activity_id':9/g" |\
#        sed -e "s/$/,'issue_id':$ID/g" |\
#        sed -e "s/^/{'time_entry':{/g" -e "s/$/}}/g" -e "s/'/\"/g" |\
#        curl -X POST -H "Content-type:application/json" -s -3 -d @- "https://$SERVER/time_entries.json?key=$KEY" 
#        echo
#      done

    elif [ $(echo "$1" | grep "^spent:[0-9.]*:[0-9]\{2\}-[0-9]\{2\}:.*$") ]; then
      SPENT_HOURS=$(echo "$1" | sed 's/^spent:\(.*\):.*:.*$/\1/g')
      SPENT_ON="$(date +%Y)-$(echo "$1" | sed 's/^spent:.*:\(.*\):.*$/\1/g')"
      COMMENTS="$(echo "$1" | sed 's/^spent:.*:.*:\(.*\)$/\1/g')"
      shift
      for ID in $IDS; do
        echo "'hours':'$SPENT_HOURS'" |\
        sed -e "s/$/,'spent_on':'$SPENT_ON'/g" |\
        sed -e "s/$/,'comments':'$COMMENTS'/g" |\
        sed -e "s/$/,'activity_id':9/g" |\
        sed -e "s/$/,'issue_id':$ID/g" |\
        sed -e "s/^/{'time_entry':{/g" -e "s/$/}}/g" -e "s/'/\"/g" |\
        curl -X POST -H "Content-type:application/json" -s -3 -d @- "https://$SERVER/time_entries.json?key=$KEY" 
        echo
      done

#    elif [ $(echo "$1" | grep "^spent:[0-9]*:[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$") ]; then
#      SPENT_HOURS=$(echo "$1" | sed 's/^spent:\(.*\):.*$/\1/g')
#      SPENT_ON=$(echo "$1" | sed 's/^spent:.*:\(.*\)$/\1/g')
#      shift
#      for ID in $IDS; do
#        echo "'hours':'$SPENT_HOURS'" |\
#        sed -e "s/$/,'spent_on':'$SPENT_ON'/g" |\
#        sed -e "s/$/,'activity_id':9/g" |\
#        sed -e "s/$/,'issue_id':$ID/g" |\
#        sed -e "s/^/{'time_entry':{/g" -e "s/$/}}/g" -e "s/'/\"/g" |\
#        curl -X POST -H "Content-type:application/json" -s -3 -d @- "https://$SERVER/time_entries.json?key=$KEY" 
#        echo
#      done

    else
      break
    fi
  else
    break
  fi
done

