#!/bin/bash

while true;do
  if [ "$#" -ge 1 ]; then

    if [ $(echo "$1" | grep "filter:[a-zA-Z0-9_-]\{1,\}") ]; then
      VARIABLE_NAME=$(echo "$1" | sed 's/^filter://g')
      shift
      load_json_content_of_ids
      ALL_TASKS_JSON="$(eval $VARIABLE_NAME)"

    elif [ $(echo "$1" | grep "tags:\[.*\]$") ]; then
      FILTER_TAGS=$(echo "$1" | sed 's/^tags:\[\(.*\)\]$/\1/g')
      shift
      load_json_content_of_ids
      FILTER_TAGS=$(echo "$FILTER_TAGS" | tr ',' '\n')
      for TAG in $FILTER_TAGS; do
        if [[ $TAG =~ ^\+.*$ ]]; then
          TAG=$(echo "$TAG" | sed 's/^\+//g')
          ALL_TASKS_JSON=$(echo "$ALL_TASKS_JSON" |\
          jq -c "[.[]|\
          select( (.cjson.tags!=null) and (.cjson.tags|contains([\"$TAG\"])) )\
          ]" )
        elif [[ $TAG =~ ^-.*$ ]]; then
          TAG=$(echo "$TAG" | sed 's/^-//g')
          ALL_TASKS_JSON=$(echo "$ALL_TASKS_JSON" |\
          jq -c "[.[]|\
          select( (.cjson.tags==null) or (.cjson.tags|contains([\"$TAG\"])|not) )\
          ]" )
        fi
      done

    elif [ $(echo "$1" | grep "\<assigned:[0-9]*\>") ]; then
      USER_ID=$(echo "$1" | sed 's/^assigned://g')
      shift
      load_json_content_of_ids
      #TODO: how to provide a list of assignees
      ALL_TASKS_JSON=$(echo "$ALL_TASKS_JSON" | jq -c "[.[]| select(.assigned_to.id==$USER_ID)]" )

    elif [ $(echo "$1" | grep "\<assigned:[a-zA-Z0-9_-]*\>") ]; then
      USER_STRING=$(echo "$1" | sed 's/^assigned://g')
      shift
      load_json_content_of_ids
      #TODO: how to provide a list of assignees
      MATCHING_USER_ID="$(project_member_by_name $USER_STRING)"
      if [ -n "$MATCHING_USER_ID" ];then
        ALL_TASKS_JSON=$(echo "$ALL_TASKS_JSON" | jq -c "[.[]| select(.assigned_to.id==$MATCHING_USER_ID)]" )
      fi

    elif [[ $1 =~ ^hier($|(a$|ar$|arc$|arch$|archy$)) ]] || [ "$1" = "hrchy" ]; then
      shift
      load_json_content_of_ids
      #TODO: what to do with issues whos parent is not in the json structure
      #TODO: what to do with grandchildren
      #TODO: what to do when the children structure is already filled in the minimal form
      NO_PARENT="$(echo "$ALL_TASKS_JSON" | jq -c '[.[] | select(has("parent")|not)]')"
      WITH_PARENT="$(echo "$ALL_TASKS_JSON" | jq -c '[.[] | select(has("parent"))]')"
      IDS_WITH_PARENT="$(echo "$WITH_PARENT" | jq '.[]|.id')"
      for ID in $IDS_WITH_PARENT; do
        JSON="$(echo "$WITH_PARENT" | jq -r ".[]| select(.id==$ID)")"
        PARENT="$(echo "$JSON" | jq '.parent.id')"
        NO_PARENT="$(echo "$NO_PARENT" | jq -c "[.[] | if .id==$PARENT then .children+=[$JSON] else . end]")"
      done
      ALL_TASKS_JSON="$NO_PARENT"
      IDS="$( ids_from_json_array "$ALL_TASKS_JSON" )"

    else
      break
    fi
  else
    break
  fi
done
