#!/bin/bash

if [ -L "$0" ];then
  SCRIPT_PATH="$(dirname $(readlink $0))"
else
  SCRIPT_PATH="$(dirname $0)"
fi

source $SCRIPT_PATH/_redtask_helpers

source $SCRIPT_PATH/_redmine_api_config_file
source $SCRIPT_PATH/_redtask_options

: ${ISSUE_LIMIT:="400"}
: ${USER_ID:="me"}
: ${CHILD_DEPTH:=0}
: ${CUSTOM_JSON_KEY:="description"}
: ${CHILD_LEADING_SPACES:="    "}
IFS=$'\n'
IFS=${IFS:0:1}

if [ -z "$SERVER" ] || [ -z "$PROJECT_ID" ] || [ -z "$KEY" ]; then
  echo "SERVER,PROJECT_ID or KEY variable are not defined." >&2
  echo "  These variables should either be defined as environments variables," >&2
  echo "  or in a .redmine file in the current directory or the users home directory." >&2
  exit 1
fi

ALL_TASKS_JSON=""
IDS=""

source $SCRIPT_PATH/_redtask_filters
source $SCRIPT_PATH/_redtask_operations
source $SCRIPT_PATH/_redtask_print
source $SCRIPT_PATH/_redtask_experiment

